name: Test

on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: rm -rf node_modules
      - run: yarn install --frozen-lockfile
      - run: yarn test
        env:
          CLIENT_ID = ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET = ${{ secrets.CLIENT_SECRET }}
          PRIVATE_KEY = ${{ secrets.PRIVATE_KEY }}
