name: Test

on:
  push:
    branches: [ ci/cd ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: rm -rf node_modules
    - run: yarn install --frozen-lockfile
    - run: yarn test
